# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dekstop.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from screeninfo import get_monitors

width = get_monitors()[0].width
height = get_monitors()[0].height

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(width, height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, width/0.9994794377928162, height/1.078921078921079))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Desktop a.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(width/2.3132530120481927, height/3, width/6.378737541528239, width/6.378737541528239))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Crystal new.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(width/5.64, height/12, width/4, height/3.5))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Detail.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(width/12, height/3, width/4, height/3.5))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Detail.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(width/5.33, height/1.7142857142857142, width/4, height/3.5))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Detail.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(width/2.18, height/8.30, width/7.08, height/10.69))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/27)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background: transparent; color: white; border: none;")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(width/2.3132530120481927, height/3, width/6.378737541528239, height/3.711340206185567))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: white; background: transparent; border-radius: 145px;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(width/2.64, height/1.63, width/4.45, height/1.13))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/54)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background: transparent; color: white; border: none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(width/4.92, height/7.71, width/5.8, height/18))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/54)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textBrowser_3.setStyleSheet("background: transparent; color: white; border: none;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(width/4.92, height/5.4, width/5.8, height/18))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(height/54)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setStyleSheet("background: transparent; color: white; border: none;")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(width/1.71, height/18, width/2.7, height/2.24))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Details.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(width/1.71, height/2.20, width/2.7, height/2.24))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Details.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(width/1.5737704918032787, height/1.8305084745762712, width/3.7573385518590996, height/17.704918032786885))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(24)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(width/1.5737704918032787, height/6.75, width/3.7573385518590996, height/17.704918032786885))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(24)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: white;")
        self.label_10.setObjectName("label_10")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(width/4.923076923076923, height/4.153846153846154, width/5.80060422960725, height/18.0))
        font = QtGui.QFont()
        font.setFamily("Dash Horizon")
        font.setPointSize(20)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setStyleSheet("background: transparent; color: white; border: none;")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(width/1.5238095238095237, height/4.5, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("background: transparent; color: white;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(width/1.5238095238095237, height/3.176470588235294, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setStyleSheet("background: transparent; color: white;")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(width/1.28, height/4.5, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setStyleSheet("background: transparent; color: white;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(width/1.1851851851851851, height/3.176470588235294, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setStyleSheet("background: transparent; color: white;")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(width/1.391304347826087, height/4.5, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("background: transparent; color: white;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(width/1.1851851851851851, height/4.5, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setStyleSheet("background: transparent; color: white;")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(width/1.28, height/3.176470588235294, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_7.setStyleSheet("background: transparent; color: white;")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(width/1.391304347826087, height/3.176470588235294, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_8.setStyleSheet("background: transparent; color: white;")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(width/1.28, height/1.6363636363636365, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_10.setStyleSheet("background: transparent; color: white;")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(width/1.1851851851851851, height/1.4210526315789473, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_11.setStyleSheet("background: transparent; color: white;")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(width/1.28, height/1.4210526315789473, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_12.setStyleSheet("background: transparent; color: white;")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(width/1.1851851851851851, height/1.6363636363636365, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_13.setStyleSheet("background: transparent; color: white;")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(width/1.5238095238095237, height/1.6363636363636365, width/27.04225352112676, height/15.211267605633802))
        self.pushButton_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_14.setStyleSheet("background: transparent; color: white;")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Apps/Discover.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setIconSize(QtCore.QSize(width/27.04225352112676, height/15.211267605633802))
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(width/1.391304347826087, height/1.6363636363636365, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_15.setStyleSheet("background: transparent; color: white;")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(width/1.391304347826087, height/1.4210526315789473, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_16.setStyleSheet("background: transparent; color: white;")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(width/1.5238095238095237, height/1.4210526315789473, width/27.04225352112676, height/17.704918032786885))
        self.pushButton_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_17.setStyleSheet("background: transparent; color: white;")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.textBrowser.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser_3.raise_()
        self.textBrowser_4.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.textBrowser_5.raise_()
        self.pushButton_4.raise_()
        self.pushButton_9.raise_()
        self.pushButton_7.raise_()
        self.pushButton_5.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_6.raise_()
        self.pushButton_8.raise_()
        self.pushButton_14.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_15.raise_()
        self.pushButton_17.raise_()
        self.pushButton_16.raise_()
        self.pushButton_10.raise_()
        self.textBrowser_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser_3.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser_4.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "System Apps"))
        self.label_10.setText(_translate("MainWindow", "Desktop Shortcuts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

